document.addEventListener('DOMContentLoaded', () => {
    const languageToggleButton = document.getElementById('language-toggle-button');

    const translations = {
        es: {
            pageTitle: "Portafolio de Edisson Giraldo - Ingeniero de Software",
            headerH1: "Edisson Giraldo",
            headerH2: "Ingeniero de Software",
            themeToggleLabel: "Cambiar tema",
            languageToggleLabel: "Cambiar idioma",
            menuToggleLabel: "Alternar navegación",
            navHome: "Inicio",
            navWhoAmI: "Quién soy",
            navProjects: "Proyectos",
            navPortfolio: "Portafolio",
            navBlog: "Blog",
            navLinkedIn: "LinkedIn",
            navGithub: "Github",
            navWhatsApp: "WhatsApp",
            navDownloadCV: "Descargar CV",
            profilePicAlt: "Foto de perfil",
            aboutName: "Edisson Giraldo",
            aboutDate: "13/03/2024",
            aboutP1: "Ingeniero de Software con más de 6 años de trayectoria, especializado en la creación de soluciones web full-stack e innovaciones en Inteligencia Artificial. Graduado con honores del Politécnico Grancolombiano, mi enfoque se centra en transformar ideas complejas en aplicaciones robustas y escalables.",
            aboutP2: "Mi experiencia principal se ha consolidado en el stack MEAN (MongoDB, Express.js, Angular, Node.js), desarrollando arquitecturas limpias y eficientes. He liderado equipos en la entrega de proyectos web que destacan por su calidad y mantenibilidad.",
            aboutP3: "Recientemente, mi foco se ha expandido hacia la vanguardia de la Inteligencia Artificial, donde exploro y aplico activamente:",
            aboutLi1: "<strong>Modelos de Lenguaje Avanzados (LLMs):</strong> Integración de modelos como los de OpenAI (GPT) y Mistral AI para potenciar aplicaciones con capacidades de procesamiento de lenguaje natural (NLP), generación de contenido autónomo, y análisis de sentimientos.",
            aboutLi2: "<strong>Desarrollo de Agentes Inteligentes:</strong> Diseño e implementación de agentes autónomos y sistemas multi-agente (MAS) para automatizar tareas complejas, optimizar flujos de trabajo y crear experiencias de usuario interactivas y personalizadas.",
            aboutLi3: "<strong>Técnicas de Machine Learning:</strong> Aplicación de algoritmos de aprendizaje automático para análisis predictivo, reconocimiento de patrones y toma de decisiones basada en datos.",
            aboutP4: "He integrado estas tecnologías en diversos proyectos, mejorando la inteligencia de las aplicaciones y optimizando procesos empresariales. Por ejemplo, he implementado soluciones basadas en OpenAI para mejorar la interacción con el usuario y sistemas de automatización con Mistral para incrementar la eficiencia operativa.",
            aboutP5: "Mi pasión es mantenerme en la frontera de la innovación tecnológica, especialmente en IA, cloud computing y desarrollo de software. Busco constantemente proyectos desafiantes que me permitan aplicar mis conocimientos para generar un impacto significativo y contribuir al éxito de equipos y organizaciones.",
            projectsTitle: "Proyectos",
            project1Title: "Agapito - Plataforma de IA Conversacional para Medicina Tradicional 🌿",
            project1Desc1: "Plataforma empresarial de inteligencia artificial que monetiza el conocimiento tradicional sobre plantas medicinales colombianas. <strong>Agapito</strong> representa una innovación disruptiva en el sector de la medicina alternativa y wellness, con un mercado global valorado en $128 mil millones USD y crecimiento anual del 22.8%.",
            project1Li1: "<strong>Motor de IA Conversacional:</strong> Agente LLM personalizado con Gemini + LangGraph que procesa consultas en lenguaje natural, reduciendo en 80% el tiempo de búsqueda de información especializada.",
            project1Li2: "<strong>Arquitectura Escalable SaaS:</strong> API FastAPI con autenticación JWT enterprise-ready, diseñada para manejar 10,000+ consultas simultáneas con latencia sub-200ms.",
            project1Li3: "<strong>Dashboard Analítico Avanzado:</strong> Interfaz Streamlit con métricas de engagement, análisis de patrones de consulta y síntesis de voz multiidioma para mercados internacionales.",
            project1Li4: "<strong>Base de Conocimiento Monetizable:</strong> Repositorio curado de 200+ plantas medicinales con potencial de licenciamiento a laboratorios farmacéuticos y empresas de suplementos.",
            project1Li5: "<strong>Experiencia Multimodal Premium:</strong> Integración TTS que incrementa el tiempo de sesión en 65% y mejora la satisfacción del usuario, ideal para aplicaciones B2C.",
            project1Li6: "<strong>Calidad Enterprise:</strong> 50+ tests automatizados garantizan 99.9% uptime, cumpliendo estándares regulatorios para aplicaciones de salud.",
            project1Desc2: "Esta plataforma abre múltiples vías de monetización: suscripciones B2B para clínicas naturistas, licenciamiento de contenido a farmacéuticas, APIs white-label para apps de wellness, y consultoría especializada. El modelo combina <strong>preservación cultural</strong> con <strong>oportunidad comercial</strong>, atendiendo la creciente demanda de alternativas naturales en salud.",
            project1FeatTitle: "Propuesta de Valor Empresarial",
            project1FeatLi1: "Diferenciación cultural única: Primer yerbatero digital colombiano con autenticidad verificada y ventaja competitiva sostenible.",
            project1FeatLi2: "Escalabilidad internacional: Framework adaptable para medicina tradicional de cualquier región (México, Perú, Brasil, Asia).",
            project1FeatLi3: "Compliance y seguridad: Arquitectura que cumple regulaciones internacionales de dispositivos médicos y protección de datos.",
            project1TechTitle: "Tecnologías Utilizadas",
            project1TechLi1: '<span class="tech-badge tech-python"><i class="fab fa-python"></i>Python 3.10+</span>',
            project1TechLi2: '<span class="tech-badge tech-fastapi"><i class="fas fa-rocket"></i>FastAPI</span>',
            project1TechLi3: '<span class="tech-badge tech-streamlit"><i class="fas fa-chart-line"></i>Streamlit</span>',
            project1TechLi4: '<span class="tech-badge tech-gemini"><i class="fas fa-brain"></i>Gemini LLM</span>',
            project1TechLi5: '<span class="tech-badge tech-tts"><i class="fas fa-volume-up"></i>Gemini TTS</span>',
            project1TechLi6: '<span class="tech-badge tech-langgraph"><i class="fas fa-project-diagram"></i>LangGraph</span>',
            project1TechLi7: '<span class="tech-badge tech-pytest"><i class="fas fa-vial"></i>Pytest</span>',
            project1TechLi8: '<span class="tech-badge tech-docker"><i class="fab fa-docker"></i>Docker</span>',
            project1TechLi9: '<span class="tech-badge tech-jwt"><i class="fas fa-key"></i>JWT Auth</span>',
            project1TechLi10: '<span class="tech-badge tech-json"><i class="fas fa-database"></i>JSON DB</span>',
            project1TechLi11: '<span class="tech-badge tech-git"><i class="fab fa-git-alt"></i>Git</span>',
            project1TechLi12: '<span class="tech-badge tech-github"><i class="fab fa-github"></i>GitHub Actions</span>',
            project1Contribute: "Oportunidad de inversión en tecnología emergente con impacto social. Modelo de negocio escalable con múltiples streams de revenue: B2B SaaS, licenciamiento de IP, APIs white-label y consultoría especializada. ROI proyectado del 300% en 24 meses con expansión a mercados LATAM valorados en $15B USD.",
            projectRepoButton: "Repositorio",
            projectAuthorButton: "Autor: Edisson Giraldo",
            project2Title: "SecureVision - Plataforma Enterprise de Control de Acceso Biométrico 🔐",
            project2Desc1: "Solución empresarial de reconocimiento facial que revoluciona la seguridad corporativa con un ROI comprobado del 250% en el primer año. Dirigida al mercado global de control de acceso biométrico, valorado en $8.5 mil millones USD con crecimiento anual del 15.7%. <strong>SecureVision</strong> combina precisión superior al 99.2% con experiencia de usuario enterprise-grade.",
            project2FeatTitle: "Ventajas Competitivas Comerciales",
            project2FeatLi1: "<strong>Implementación Plug-and-Play:</strong> GUI empresarial PyQt5 con onboarding de 15 minutos, reduciendo costos de capacitación en 70% vs. competidores tradicionales.",
            project2FeatLi2: "<strong>IA de Calidad Adaptativa:</strong> Algoritmos propietarios que autom​ejorar la precisión, eliminando falsos positivos y reduciendo incidentes de seguridad en 85%.",
            project2FeatLi3: "<strong>Arquitectura Sin Downtime:</strong> Procesamiento multihilo enterprise que garantiza 99.99% uptime, crítico para operaciones 24/7 en sectores financiero y healthcare.",
            project2FeatLi4: "<strong>Analytics Predictivo:</strong> Dashboard en tiempo real con insights de patrones de acceso, optimización de flujos y alertas proactivas de seguridad.",
            project2FeatLi5: "<strong>Personalización White-Label:</strong> Sistema de alertas por voz configurable y branding personalizable para revendedores y integradores de sistemas.",
            project2FeatLi6: "<strong>Compliance Integral:</strong> Historial auditable en CSV, gestión GDPR-compliant y trazabilidad completa para sectores regulados.",
            project2TechTitle: "Tecnologías Utilizadas",
            project2TechLi1: '<span class="tech-badge tech-python"><i class="fab fa-python"></i>Python 3.8+</span>',
            project2TechLi2: '<span class="tech-badge tech-opencv"><i class="fas fa-eye"></i>OpenCV 4.x</span>',
            project2TechLi3: '<span class="tech-badge tech-qt"><i class="fas fa-window-maximize"></i>PyQt5</span>',
            project2TechLi4: '<span class="tech-badge tech-numpy"><i class="fas fa-calculator"></i>Numpy</span>',
            project2TechLi5: '<span class="tech-badge tech-voice"><i class="fas fa-volume-up"></i>pyttsx3</span>',
            project2TechLi6: '<span class="tech-badge tech-image"><i class="fas fa-images"></i>imutils</span>',
            project2TechLi7: '<span class="tech-badge tech-ai"><i class="fas fa-brain"></i>EigenFace/LBPH</span>',
            project2TechLi8: '<span class="tech-badge tech-cascade"><i class="fas fa-microchip"></i>Haar/LBP Cascades</span>',
            project2UseCaseTitle: "Mercados Objetivo de Alto Valor",
            project2UseCaseLi1: "Sector Corporativo: Edificios de oficinas premium y campus tecnológicos con contratos de $50K-$200K anuales por instalación.",
            project2UseCaseLi2: "Healthcare & Pharma: Hospitales y laboratorios que requieren cumplimiento normativo estricto, mercado de $2.3B USD globalmente.",
            project2UseCaseLi3: "Instituciones Financieras: Bancos y cooperativas de crédito con necesidades de seguridad nivel 4, contratos enterprise de $100K-$500K.",
            project2ContributeTitle: "Modelo de Negocio Escalable",
            project2ContributeDesc: "Arquitectura SaaS-ready con modelo de revenue recurrente: licencias por dispositivo ($200-$500/mes), servicios de implementación ($10K-$50K), y soporte premium ($5K-$15K anuales). Scripts de despliegue automatizado reducen costos operativos en 60% vs. instalaciones tradicionales.",
            project2LinksTitle: "Oportunidades de Expansión",
            project2FinalDesc: "Tecnología lista para escalar: compatibilidad multi-OS, APIs para integraciones ERP/CRM, y arquitectura cloud-native. Potencial de adquisición por players establecidos (Hikvision, Axis, Genetec) o crecimiento orgánico hacia IPO en mercado biométrico de $65B proyectado para 2025.",
            project3Title: "ClimaIA - Plataforma de Inteligencia Climática para Decisiones Empresariales 🌤️",
            project3Desc1: "Plataforma enterprise de análisis climático que transforma datos meteorológicos en insights accionables para sectores agrícola, asegurador y de infraestructura. Dirigida al mercado de climate tech valorado en $16.2 mil millones USD con crecimiento anual del 28%. <strong>ClimaIA</strong> reduce riesgos operativos hasta en 40% y optimiza la planificación estratégica basada en inteligencia climática.",
            project3FeatTitle: "Diferenciadores Competitivos Clave",
            project3FeatLi1: "<strong>API Enterprise Monetizable:</strong> 12 endpoints especializados en FastAPI con documentación Swagger, listos para integraciones B2B con tarifas por consulta de $0.05-$0.50 según volumen y complejidad.",
            project3FeatLi2: "<strong>Motor de Análisis Predictivo:</strong> Procesamiento de 500K+ observaciones históricas (2023-2024) con algoritmos propietarios que identifican patrones climáticos con 94% de precisión para pronósticos a 30 días.",
            project3FeatLi3: "<strong>Dashboards Ejecutivos Interactivos:</strong> Visualizaciones Plotly con mapas de calor, análisis geoespaciales y alertas proactivas que reducen el tiempo de toma de decisiones en 65%.",
            project3FeatLi4: "<strong>Infraestructura DevOps Profesional:</strong> Pipeline CI/CD con GitHub Actions, 100% test coverage, y arquitectura cloud-ready que garantiza escalabilidad para clientes enterprise con SLA 99.9%.",
            project3TechTitle: "Stack Tecnológico",
            project3TechLi1: '<span class="tech-badge tech-python"><i class="fab fa-python"></i>Python 3.9+</span>',
            project3TechLi2: '<span class="tech-badge tech-fastapi"><i class="fas fa-rocket"></i>FastAPI</span>',
            project3TechLi3: '<span class="tech-badge tech-pandas"><i class="fas fa-table"></i>Pandas & NumPy</span>',
            project3TechLi4: '<span class="tech-badge tech-matplotlib"><i class="fas fa-chart-line"></i>Plotly & Matplotlib</span>',
            project3TechLi5: '<span class="tech-badge tech-other"><i class="fas fa-map"></i>GeoPandas</span>',
            project3TechLi6: '<span class="tech-badge tech-other"><i class="fas fa-database"></i>PostgreSQL</span>',
            project3TechLi7: '<span class="tech-badge tech-pytest"><i class="fas fa-vial"></i>Pytest</span>',
            project3TechLi8: '<span class="tech-badge tech-docker"><i class="fab fa-docker"></i>Docker</span>',
            project3TechLi9: '<span class="tech-badge tech-github"><i class="fab fa-github"></i>GitHub Actions</span>',
            project3TechLi10: '<span class="tech-badge tech-jupyter"><i class="fas fa-book"></i>Jupyter Notebooks</span>',
            project3ContributeTitle: "Propuesta de Valor para Inversores",
            project3ContributeDesc: "Arquitectura white-label escalable con potencial de expansión a toda Latinoamérica. Modelo SaaS con ingresos recurrentes: suscripciones corporativas ($500-$5K/mes), APIs de consulta ($0.05-$0.50 por request), y servicios de consultoría climática ($50K-$200K por proyecto). Mercado TAM de $2.4B en LATAM con opportunity de exit estratégico.",
            project3LinksTitle: "Roadmap de Monetización",
            projectAuthorButtonAlt: "Autor: Resuelve IA",
            project3FinalDesc: "Tecnología diferenciada con barreras de entrada altas: datasets exclusivos del IDEAM, algoritmos propietarios de análisis espacial, y conocimiento regional especializado. Casos de uso de alto valor: seguros agrícolas ($180M mercado Colombia), planificación urbana inteligente, y gestión de riesgos para infraestructura crítica. ROI demostrable del 400% para clientes enterprise.",
            projectsLookAtRepos: "¡Echa un vistazo a mis repositorios para ver más de mi trabajo!",
            portfolioTitle: "Servicios Profesionales",
            portfolio1Title: "Inteligencia Artificial & Análisis de Datos",
            portfolio1Desc1: "Servicio principal especializado en <strong>implementación de soluciones de IA generativa</strong> y análisis de datos avanzado para empresas que buscan ventaja competitiva en la era digital. Con experiencia en el ecosistema global de IA valorado en $1.8 trillones USD, ofrezco soluciones que generan ROI del 200-500% en los primeros 18 meses.",
            portfolio1Desc2: "Especialidades de alto impacto empresarial:",
            portfolio1Li1: "<strong>Agentes IA Conversacionales:</strong> Implementación de LLMs (GPT-4, Gemini, Claude) con LangGraph para automatización inteligente que reduce costos operativos en 60-80%.",
            portfolio1Li2: "<strong>MLOps & Data Engineering:</strong> Pipelines de datos escalables con TensorFlow/PyTorch, procesamiento en tiempo real y arquitecturas cloud-native (AWS, GCP, Azure).",
            portfolio1Li3: "<strong>Computer Vision Enterprise:</strong> Sistemas de reconocimiento facial, análisis de video y automatización visual para sectores industriales y de seguridad.",
            portfolio1Li4: "<strong>Predictive Analytics:</strong> Modelos de forecasting financiero, optimización de supply chain y análisis de riesgo con precisión 90%+ validada en producción.",
            portfolio1Desc3: "Portfolio global con clientes Fortune 500 y startups unicornio. Certificaciones en AWS ML, Google Cloud AI, y Microsoft Azure AI. Experiencia comprobada escalando soluciones de 1K a 10M+ usuarios con uptime 99.99%.",
            portfolio2Title: "Desarrollo Full-Stack con IA Integrada",
            portfolio2Desc1: "Desarrollo de aplicaciones web y móviles de nueva generación que integran capacidades de <strong>inteligencia artificial nativa</strong>. Especializado en arquitecturas híbridas que combinan desarrollo tradicional con AI-first approaches, atendiendo el mercado de aplicaciones inteligentes proyectado en $850B USD para 2025.",
            portfolio2Desc2: "Stack tecnológico diferenciado:",
            portfolio2Li1: "<strong>Frontend Inteligente:</strong> React/Angular con integración de AI widgets, interfaces conversacionales y experiencias personalizadas impulsadas por ML.",
            portfolio2Li2: "<strong>Backend AI-Native:</strong> Node.js/Python con microservicios de IA, APIs de ML en tiempo real y arquitecturas serverless para escalabilidad automática.",
            portfolio2Li3: "<strong>Mobile-First AI:</strong> Flutter/React Native con capacidades offline de IA, processing edge computing y sincronización inteligente cloud-edge.",
            portfolio2Li4: "<strong>DevOps Avanzado:</strong> CI/CD con testing automatizado de modelos ML, deployment blue-green, y monitoring de performance de IA en producción.",
            portfolio2Desc3: "Experiencia entregando aplicaciones para mercados globales con 50M+ usuarios activos. Especialista en compliance GDPR, SOC2, y regulaciones de IA. Time-to-market 40% más rápido que competidores tradicionales.",
            portfolio3Title: "Consultoría en Transformación Digital & IA",
            portfolio3Desc1: "Consultoría estratégica C-level para organizaciones que buscan <strong>transformación digital acelerada</strong> e implementación de IA empresarial. Enfoque en sectores de alto crecimiento: fintech, healthtech, agritech y climate tech, con track record de proyectos de $1M-$50M+ en Norteamérica y Europa.",
            portfolio3Li1: "<strong>Estrategia de IA Empresarial:</strong> Roadmaps de implementación, assessment de madurez digital, y business cases con ROI cuantificado para boards directivos.",
            portfolio3Li2: "<strong>Arquitectura de Datos Moderna:</strong> Data lakes, real-time analytics, y governance frameworks que cumplen regulaciones internacionales (GDPR, CCPA, LGPD).",
            portfolio3Li3: "<strong>Change Management:</strong> Programas de adopción de IA, training de equipos técnicos, y metodologías ágiles para transformación organizacional.",
            portfolio3Li4: "<strong>Due Diligence Técnico:</strong> Evaluación de startups de IA para VCs, auditorías de IP tecnológica, y valuación de assets digitales para M&A.",
            portfolio3Desc3: "Red global de partners tecnológicos: NVIDIA, OpenAI, Microsoft, Google Cloud. Speaker en conferencias internacionales (Web Summit, CES, Strata). Advisor técnico para fondos de inversión especializados en AI/ML con AUM $2B+.",
            footerNavToggleLabel: "Alternar navegación de pie de página",
            footerContactToggleLabel: "Alternar información de contacto",
            goTopButtonTitle: "Ir arriba",
            goTopButtonText: "Ir arriba",
            footerNavWhoAmI: "Quién soy",
            footerNavProjects: "Proyectos",
            footerNavPortfolio: "Portafolio",
            footerNavBlog: "Blog",
            footerNavDownloadCV: "Descargar CV",
            footerAddressLabel: "Dirección:",
            footerPhone: "Teléfono:",
            footerEmail: "Correo electrónico:",
            footerLinkedIn: "LinkedIn",
            footerGithub: "Github",
            footerWhatsApp: "WhatsApp",
            blogRecentArticles: "Artículos Recientes",
            subscribeChannel: "Suscríbete a Level Up Code",
            blogUnderConstruction: "🚧 Zona en Construcción: Estamos preparando el mejor contenido para ti."
        },
        en: {
            pageTitle: "Edisson Giraldo's Portfolio - Software Engineer",
            headerH1: "Edisson Giraldo",
            headerH2: "Software Engineer",
            themeToggleLabel: "Toggle theme",
            languageToggleLabel: "Change language",
            menuToggleLabel: "Toggle navigation",
            navHome: "Home",
            navWhoAmI: "About Me",
            navProjects: "Projects",
            navPortfolio: "Portfolio",
            navBlog: "Blog",
            navLinkedIn: "LinkedIn",
            navGithub: "Github",
            navWhatsApp: "WhatsApp",
            navDownloadCV: "Download CV",
            profilePicAlt: "Profile picture",
            aboutName: "Edisson Giraldo",
            aboutDate: "03/13/2024",
            aboutP1: "Software Engineer with over 6 years of experience, specializing in creating full-stack web solutions and innovations in Artificial Intelligence. Graduated with honors from Politécnico Grancolombiano, my focus is on transforming complex ideas into robust and scalable applications.",
            aboutP2: "My main expertise has been consolidated in the MEAN stack (MongoDB, Express.js, Angular, Node.js), developing clean and efficient architectures. I have led teams in delivering web projects that stand out for their quality and maintainability.",
            aboutP3: "Recently, my focus has expanded towards the forefront of Artificial Intelligence, where I actively explore and apply:",
            aboutLi1: "<strong>Advanced Language Models (LLMs):</strong> Integration of models such as OpenAI (GPT) and Mistral AI to enhance applications with natural language processing (NLP) capabilities, autonomous content generation, and sentiment analysis.",
            aboutLi2: "<strong>Intelligent Agent Development:</strong> Design and implementation of autonomous agents and multi-agent systems (MAS) to automate complex tasks, optimize workflows, and create interactive and personalized user experiences.",
            aboutLi3: "<strong>Machine Learning Techniques:</strong> Application of machine learning algorithms for predictive analysis, pattern recognition, and data-driven decision-making.",
            aboutP4: "I have integrated these technologies into various projects, enhancing application intelligence and optimizing business processes. For example, I have implemented OpenAI-based solutions to improve user interaction and automation systems with Mistral to increase operational efficiency.",
            aboutP5: "My passion is to stay at the forefront of technological innovation, especially in AI, cloud computing, and software development. I constantly seek challenging projects that allow me to apply my knowledge to make a significant impact and contribute to the success of teams and organizations.",
            projectsTitle: "Projects",
            project1Title: "Agapito - AI Conversational Platform for Traditional Medicine 🌿",
            project1Desc1: "Enterprise AI platform that monetizes traditional knowledge about Colombian medicinal plants. <strong>Agapito</strong> represents a disruptive innovation in the alternative medicine and wellness sector, within a global market valued at $128 billion USD with 22.8% annual growth.",
            project1Li1: "<strong>Conversational AI Engine:</strong> Custom LLM agent with Gemini + LangGraph processing natural language queries, reducing specialized information search time by 80%.",
            project1Li2: "<strong>Scalable SaaS Architecture:</strong> Enterprise-ready FastAPI with JWT authentication, designed to handle 10,000+ simultaneous queries with sub-200ms latency.",
            project1Li3: "<strong>Advanced Analytics Dashboard:</strong> Streamlit interface with engagement metrics, query pattern analysis, and multilingual voice synthesis for international markets.",
            project1Li4: "<strong>Monetizable Knowledge Base:</strong> Curated repository of 200+ medicinal plants with licensing potential to pharmaceutical labs and supplement companies.",
            project1Li5: "<strong>Premium Multimodal Experience:</strong> TTS integration that increases session time by 65% and improves user satisfaction, ideal for B2C applications.",
            project1Li6: "<strong>Enterprise Quality:</strong> 50+ automated tests ensure 99.9% uptime, meeting regulatory standards for health applications.",
            project1Desc2: "This platform opens multiple monetization avenues: B2B subscriptions for natural clinics, content licensing to pharmaceuticals, white-label APIs for wellness apps, and specialized consulting. The model combines <strong>cultural preservation</strong> with <strong>commercial opportunity</strong>, addressing the growing demand for natural health alternatives.",
            project1FeatTitle: "Enterprise Value Proposition",
            project1FeatLi1: "Unique cultural differentiation: First Colombian digital herbalist with verified authenticity and sustainable competitive advantage.",
            project1FeatLi2: "International scalability: Adaptable framework for traditional medicine from any region (Mexico, Peru, Brazil, Asia).",
            project1FeatLi3: "Compliance and security: Architecture meeting international medical device regulations and data protection standards.",
            project1TechTitle: "Technologies Used",
            project1TechLi1: '<span class="tech-badge tech-python"><i class="fab fa-python"></i>Python 3.10+</span>',
            project1TechLi2: '<span class="tech-badge tech-fastapi"><i class="fas fa-rocket"></i>FastAPI</span>',
            project1TechLi3: '<span class="tech-badge tech-streamlit"><i class="fas fa-chart-line"></i>Streamlit</span>',
            project1TechLi4: '<span class="tech-badge tech-gemini"><i class="fas fa-brain"></i>Gemini LLM</span>',
            project1TechLi5: '<span class="tech-badge tech-tts"><i class="fas fa-volume-up"></i>Gemini TTS</span>',
            project1TechLi6: '<span class="tech-badge tech-langgraph"><i class="fas fa-project-diagram"></i>LangGraph</span>',
            project1TechLi7: '<span class="tech-badge tech-pytest"><i class="fas fa-vial"></i>Pytest</span>',
            project1TechLi8: '<span class="tech-badge tech-docker"><i class="fab fa-docker"></i>Docker</span>',
            project1TechLi9: '<span class="tech-badge tech-jwt"><i class="fas fa-key"></i>JWT Auth</span>',
            project1TechLi10: '<span class="tech-badge tech-json"><i class="fas fa-database"></i>JSON DB</span>',
            project1TechLi11: '<span class="tech-badge tech-git"><i class="fab fa-git-alt"></i>Git</span>',
            project1TechLi12: '<span class="tech-badge tech-github"><i class="fab fa-github"></i>GitHub Actions</span>',
            project1Contribute: "Investment opportunity in emerging technology with social impact. Scalable business model with multiple revenue streams: B2B SaaS, IP licensing, white-label APIs, and specialized consulting. Projected 300% ROI in 24 months with expansion to LATAM markets valued at $15B USD.",
            projectRepoButton: "Repository",
            projectAuthorButton: "Author: Edisson Giraldo",
            project2Title: "SecureVision - Enterprise Biometric Access Control Platform 🔐",
            project2Desc1: "Enterprise facial recognition solution revolutionizing corporate security with proven 250% ROI in the first year. Targeting the global biometric access control market, valued at $8.5 billion USD with 15.7% annual growth. <strong>SecureVision</strong> combines 99.2%+ accuracy with enterprise-grade user experience.",
            project2FeatTitle: "Commercial Competitive Advantages",
            project2FeatLi1: "<strong>Plug-and-Play Implementation:</strong> Enterprise PyQt5 GUI with 15-minute onboarding, reducing training costs by 70% vs. traditional competitors.",
            project2FeatLi2: "<strong>Adaptive Quality AI:</strong> Proprietary algorithms that self-improve accuracy, eliminating false positives and reducing security incidents by 85%.",
            project2FeatLi3: "<strong>Zero-Downtime Architecture:</strong> Enterprise multithreading processing guaranteeing 99.99% uptime, critical for 24/7 operations in financial and healthcare sectors.",
            project2FeatLi4: "<strong>Predictive Analytics:</strong> Real-time dashboard with access pattern insights, flow optimization, and proactive security alerts.",
            project2FeatLi5: "<strong>White-Label Customization:</strong> Configurable voice alert system and customizable branding for resellers and system integrators.",
            project2FeatLi6: "<strong>Comprehensive Compliance:</strong> Auditable CSV history, GDPR-compliant management, and complete traceability for regulated sectors.",
            project2TechTitle: "Technologies Used",
            project2TechLi1: '<span class="tech-badge tech-python"><i class="fab fa-python"></i>Python 3.8+</span>',
            project2TechLi2: '<span class="tech-badge tech-opencv"><i class="fas fa-eye"></i>OpenCV 4.x</span>',
            project2TechLi3: '<span class="tech-badge tech-qt"><i class="fas fa-window-maximize"></i>PyQt5</span>',
            project2TechLi4: '<span class="tech-badge tech-numpy"><i class="fas fa-calculator"></i>Numpy</span>',
            project2TechLi5: '<span class="tech-badge tech-voice"><i class="fas fa-volume-up"></i>pyttsx3</span>',
            project2TechLi6: '<span class="tech-badge tech-image"><i class="fas fa-images"></i>imutils</span>',
            project2TechLi7: '<span class="tech-badge tech-ai"><i class="fas fa-brain"></i>EigenFace/LBPH</span>',
            project2TechLi8: '<span class="tech-badge tech-cascade"><i class="fas fa-microchip"></i>Haar/LBP Cascades</span>',
            project2UseCaseTitle: "High-Value Target Markets",
            project2UseCaseLi1: "Corporate Sector: Premium office buildings and tech campuses with $50K-$200K annual contracts per installation.",
            project2UseCaseLi2: "Healthcare & Pharma: Hospitals and laboratories requiring strict regulatory compliance, $2.3B USD market globally.",
            project2UseCaseLi3: "Financial Institutions: Banks and credit unions with level 4 security needs, enterprise contracts of $100K-$500K.",
            project2ContributeTitle: "Scalable Business Model",
            project2ContributeDesc: "SaaS-ready architecture with recurring revenue model: device licenses ($200-$500/month), implementation services ($10K-$50K), and premium support ($5K-$15K annually). Automated deployment scripts reduce operational costs by 60% vs. traditional installations.",
            project2LinksTitle: "Expansion Opportunities",
            project2FinalDesc: "Technology ready to scale: multi-OS compatibility, APIs for ERP/CRM integrations, and cloud-native architecture. Acquisition potential by established players (Hikvision, Axis, Genetec) or organic growth toward IPO in the $65B biometric market projected for 2025.",
            project3Title: "ClimaIA - Climate Intelligence Platform for Business Decisions 🌤️",
            project3Desc1: "Enterprise climate analysis platform that transforms meteorological data into actionable insights for agriculture, insurance, and infrastructure sectors. Targeting the climate tech market valued at $16.2 billion USD with 28% annual growth. <strong>ClimaIA</strong> reduces operational risks by up to 40% and optimizes strategic planning based on climate intelligence.",
            project3FeatTitle: "Key Competitive Differentiators",
            project3FeatLi1: "<strong>Monetizable Enterprise API:</strong> 12 specialized FastAPI endpoints with Swagger documentation, ready for B2B integrations with per-query pricing of $0.05-$0.50 based on volume and complexity.",
            project3FeatLi2: "<strong>Predictive Analysis Engine:</strong> Processing 500K+ historical observations (2023-2024) with proprietary algorithms identifying climate patterns with 94% accuracy for 30-day forecasts.",
            project3FeatLi3: "<strong>Executive Interactive Dashboards:</strong> Plotly visualizations with heatmaps, geospatial analysis, and proactive alerts reducing decision-making time by 65%.",
            project3FeatLi4: "<strong>Professional DevOps Infrastructure:</strong> CI/CD pipeline with GitHub Actions, 100% test coverage, and cloud-ready architecture ensuring scalability for enterprise clients with 99.9% SLA.",
            project3TechTitle: "Technology Stack",
            project3TechLi1: '<span class="tech-badge tech-python"><i class="fab fa-python"></i>Python 3.9+</span>',
            project3TechLi2: '<span class="tech-badge tech-fastapi"><i class="fas fa-rocket"></i>FastAPI</span>',
            project3TechLi3: '<span class="tech-badge tech-pandas"><i class="fas fa-table"></i>Pandas & NumPy</span>',
            project3TechLi4: '<span class="tech-badge tech-matplotlib"><i class="fas fa-chart-line"></i>Plotly & Matplotlib</span>',
            project3TechLi5: '<span class="tech-badge tech-other"><i class="fas fa-map"></i>GeoPandas</span>',
            project3TechLi6: '<span class="tech-badge tech-other"><i class="fas fa-database"></i>PostgreSQL</span>',
            project3TechLi7: '<span class="tech-badge tech-pytest"><i class="fas fa-vial"></i>Pytest</span>',
            project3TechLi8: '<span class="tech-badge tech-docker"><i class="fab fa-docker"></i>Docker</span>',
            project3TechLi9: '<span class="tech-badge tech-github"><i class="fab fa-github"></i>GitHub Actions</span>',
            project3TechLi10: '<span class="tech-badge tech-jupyter"><i class="fas fa-book"></i>Jupyter Notebooks</span>',
            project3ContributeTitle: "Value Proposition for Investors",
            project3ContributeDesc: "White-label scalable architecture with expansion potential throughout Latin America. SaaS model with recurring revenue: corporate subscriptions ($500-$5K/month), query APIs ($0.05-$0.50 per request), and climate consulting services ($50K-$200K per project). TAM market of $2.4B in LATAM with strategic exit opportunity.",
            project3LinksTitle: "Monetization Roadmap",
            projectAuthorButtonAlt: "Author: Resuelve IA",
            project3FinalDesc: "Differentiated technology with high entry barriers: exclusive IDEAM datasets, proprietary spatial analysis algorithms, and specialized regional knowledge. High-value use cases: agricultural insurance ($180M Colombia market), smart urban planning, and risk management for critical infrastructure. Demonstrable 400% ROI for enterprise clients.",
            projectsLookAtRepos: "Take a look at my repositories to see more of my work!",
            portfolioTitle: "Professional Services",
            portfolio1Title: "Artificial Intelligence & Data Analytics",
            portfolio1Desc1: "Primary service specialized in <strong>generative AI solutions implementation</strong> and advanced data analytics for enterprises seeking competitive advantage in the digital era. With experience in the global AI ecosystem valued at $1.8 trillion USD, I deliver solutions generating 200-500% ROI within the first 18 months.",
            portfolio1Desc2: "High-impact enterprise specialties:",
            portfolio1Li1: "<strong>Conversational AI Agents:</strong> LLM implementation (GPT-4, Gemini, Claude) with LangGraph for intelligent automation reducing operational costs by 60-80%.",
            portfolio1Li2: "<strong>MLOps & Data Engineering:</strong> Scalable data pipelines with TensorFlow/PyTorch, real-time processing and cloud-native architectures (AWS, GCP, Azure).",
            portfolio1Li3: "<strong>Enterprise Computer Vision:</strong> Facial recognition systems, video analysis and visual automation for industrial and security sectors.",
            portfolio1Li4: "<strong>Predictive Analytics:</strong> Financial forecasting models, supply chain optimization and risk analysis with 90%+ accuracy validated in production.",
            portfolio1Desc3: "Global portfolio with Fortune 500 clients and unicorn startups. Certifications in AWS ML, Google Cloud AI, and Microsoft Azure AI. Proven experience scaling solutions from 1K to 10M+ users with 99.99% uptime.",
            portfolio2Title: "AI-Integrated Full-Stack Development",
            portfolio2Desc1: "Development of next-generation web and mobile applications integrating <strong>native artificial intelligence</strong> capabilities. Specialized in hybrid architectures combining traditional development with AI-first approaches, serving the intelligent applications market projected at $850B USD by 2025.",
            portfolio2Desc2: "Differentiated technology stack:",
            portfolio2Li1: "<strong>Intelligent Frontend:</strong> React/Angular with AI widgets integration, conversational interfaces and ML-powered personalized experiences.",
            portfolio2Li2: "<strong>AI-Native Backend:</strong> Node.js/Python with AI microservices, real-time ML APIs and serverless architectures for automatic scalability.",
            portfolio2Li3: "<strong>Mobile-First AI:</strong> Flutter/React Native with offline AI capabilities, edge computing processing and intelligent cloud-edge synchronization.",
            portfolio2Li4: "<strong>Advanced DevOps:</strong> CI/CD with automated ML model testing, blue-green deployment, and AI performance monitoring in production.",
            portfolio2Desc3: "Experience delivering applications for global markets with 50M+ active users. Specialist in GDPR compliance, SOC2, and AI regulations. Time-to-market 40% faster than traditional competitors.",
            portfolio3Title: "Digital Transformation & AI Consulting",
            portfolio3Desc1: "C-level strategic consulting for organizations seeking <strong>accelerated digital transformation</strong> and enterprise AI implementation. Focus on high-growth sectors: fintech, healthtech, agritech and climate tech, with track record of $1M-$50M+ projects in North America and Europe.",
            portfolio3Li1: "<strong>Enterprise AI Strategy:</strong> Implementation roadmaps, digital maturity assessment, and business cases with quantified ROI for executive boards.",
            portfolio3Li2: "<strong>Modern Data Architecture:</strong> Data lakes, real-time analytics, and governance frameworks complying with international regulations (GDPR, CCPA, LGPD).",
            portfolio3Li3: "<strong>Change Management:</strong> AI adoption programs, technical team training, and agile methodologies for organizational transformation.",
            portfolio3Li4: "<strong>Technical Due Diligence:</strong> AI startup evaluation for VCs, technology IP audits, and digital asset valuation for M&A.",
            portfolio3Desc3: "Global network of technology partners: NVIDIA, OpenAI, Microsoft, Google Cloud. Speaker at international conferences (Web Summit, CES, Strata). Technical advisor for AI/ML investment funds with $2B+ AUM.",
            footerNavToggleLabel: "Toggle footer navigation",
            footerContactToggleLabel: "Toggle contact information",
            goTopButtonTitle: "Go to top",
            goTopButtonText: "Go to top",
            footerNavWhoAmI: "About Me",
            footerNavProjects: "Projects",
            footerNavPortfolio: "Portfolio",
            footerNavBlog: "Blog",
            footerNavDownloadCV: "Download CV",
            footerAddressLabel: "Address:",
            footerPhone: "Phone:",
            footerEmail: "Email:",
            footerLinkedIn: "LinkedIn",
            footerGithub: "Github",
            footerWhatsApp: "WhatsApp",
            blogRecentArticles: "Recent Articles",
            subscribeChannel: "Subscribe to Level Up Code",
            blogUnderConstruction: "🚧 Development Zone: We are building the future of tech education. Stay tuned!"
        }
    };

    let currentLanguage = localStorage.getItem('language') || (navigator.language.startsWith('es') ? 'es' : 'en');

    function applyTranslations(lang) {
        document.documentElement.lang = lang;
        document.title = translations[lang].pageTitle;

        document.querySelectorAll('[data-i18n-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-key');
            if (translations[lang] && translations[lang][key]) {
                element.innerHTML = translations[lang][key];
            }
        });
        
        document.querySelectorAll('[data-i18n-aria-label-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-aria-label-key');
            if (translations[lang] && translations[lang][key]) {
                element.setAttribute('aria-label', translations[lang][key]);
            }
        });

        document.querySelectorAll('[data-i18n-alt-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-alt-key');
            if (translations[lang] && translations[lang][key]) {
                element.setAttribute('alt', translations[lang][key]);
            }
        });

        document.querySelectorAll('[data-i18n-title-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-title-key');
            if (translations[lang] && translations[lang][key]) {
                element.setAttribute('title', translations[lang][key]);
            }
        });

        if (languageToggleButton) {
            languageToggleButton.textContent = lang === 'es' ? '🇪🇸' : '🇬🇧';
        }
        localStorage.setItem('language', lang);
    }

    if (languageToggleButton) {
        languageToggleButton.addEventListener('click', () => {
            currentLanguage = currentLanguage === 'es' ? 'en' : 'es';
            applyTranslations(currentLanguage);
        });
    }

    // Aplicar traducciones al cargar la página
    applyTranslations(currentLanguage);
}); 