document.addEventListener('DOMContentLoaded', () => {
    const languageToggleButton = document.getElementById('language-toggle-button');

    const translations = {
        es: {
            pageTitle: "Portafolio de Edisson Giraldo - Ingeniero de Software",
            headerH1: "Edisson Giraldo",
            headerH2: "Ingeniero de Software",
            themeToggleLabel: "Cambiar tema",
            languageToggleLabel: "Cambiar idioma",
            menuToggleLabel: "Alternar navegación",
            navWhoAmI: "Quién soy",
            navProjects: "Proyectos",
            navPortfolio: "Portafolio",
            navLinkedIn: "LinkedIn",
            navGithub: "Github",
            navWhatsApp: "WhatsApp",
            navDownloadCV: "Descargar CV",
            profilePicAlt: "Foto de perfil",
            aboutName: "Edisson Giraldo",
            aboutDate: "13/03/2024",
            aboutP1: "Ingeniero de Software con más de 6 años de trayectoria, especializado en la creación de soluciones web full-stack e innovaciones en Inteligencia Artificial. Graduado con honores del Politécnico Grancolombiano, mi enfoque se centra en transformar ideas complejas en aplicaciones robustas y escalables.",
            aboutP2: "Mi experiencia principal se ha consolidado en el stack MEAN (MongoDB, Express.js, Angular, Node.js), desarrollando arquitecturas limpias y eficientes. He liderado equipos en la entrega de proyectos web que destacan por su calidad y mantenibilidad.",
            aboutP3: "Recientemente, mi foco se ha expandido hacia la vanguardia de la Inteligencia Artificial, donde exploro y aplico activamente:",
            aboutLi1: "<strong>Modelos de Lenguaje Avanzados (LLMs):</strong> Integración de modelos como los de OpenAI (GPT) y Mistral AI para potenciar aplicaciones con capacidades de procesamiento de lenguaje natural (NLP), generación de contenido autónomo, y análisis de sentimientos.",
            aboutLi2: "<strong>Desarrollo de Agentes Inteligentes:</strong> Diseño e implementación de agentes autónomos y sistemas multi-agente (MAS) para automatizar tareas complejas, optimizar flujos de trabajo y crear experiencias de usuario interactivas y personalizadas.",
            aboutLi3: "<strong>Técnicas de Machine Learning:</strong> Aplicación de algoritmos de aprendizaje automático para análisis predictivo, reconocimiento de patrones y toma de decisiones basada en datos.",
            aboutP4: "He integrado estas tecnologías en diversos proyectos, mejorando la inteligencia de las aplicaciones y optimizando procesos empresariales. Por ejemplo, he implementado soluciones basadas en OpenAI para mejorar la interacción con el usuario y sistemas de automatización con Mistral para incrementar la eficiencia operativa.",
            aboutP5: "Mi pasión es mantenerme en la frontera de la innovación tecnológica, especialmente en IA, cloud computing y desarrollo de software. Busco constantemente proyectos desafiantes que me permitan aplicar mis conocimientos para generar un impacto significativo y contribuir al éxito de equipos y organizaciones.",
            projectsTitle: "Proyectos",
            project1Title: "Applied Data Science Capstone",
            project1Desc1: "Este repositorio contiene el proyecto final del curso <em>Curso Final de Ciencia de Datos Aplicada</em>, diseñado para aplicar las habilidades y conocimientos adquiridos en ciencia de datos en un caso práctico.",
            project1Li1: "<strong>Definición del problema:</strong> Identificación de un problema relevante para resolver mediante análisis de datos.",
            project1Li2: "<strong>Recolección de datos:</strong> Obtención y procesamiento de datos de fuentes relevantes.",
            project1Li3: "<strong>Análisis exploratorio de datos:</strong> Limpieza y exploración inicial para descubrir patrones y relaciones significativas.",
            project1Li4: "<strong>Modelado:</strong> Aplicación de técnicas de aprendizaje automático para resolver el problema planteado.",
            project1Li5: "<strong>Visualización:</strong> Creación de gráficos y tableros interactivos para comunicar los resultados de forma efectiva.",
            project1Li6: "<strong>Conclusiones:</strong> Recomendaciones basadas en los hallazgos obtenidos durante el análisis.",
            project1Desc2: "Este proyecto combina técnicas avanzadas de análisis de datos, modelado predictivo y visualización, utilizando herramientas como <strong>Python</strong>, <strong>Pandas</strong>, <strong>Scikit-learn</strong>, y <strong>Matplotlib</strong>, entre otras.",
            project1FeatTitle: "Características del proyecto",
            project1FeatLi1: "Enfoque en la resolución de problemas reales.",
            project1FeatLi2: "Diseño modular y reproducible para facilitar su comprensión y escalabilidad.",
            project1FeatLi3: "Código completamente documentado y alineado con las mejores prácticas.",
            project1TechTitle: "Tecnologías Utilizadas",
            project1TechLi1: "Python",
            project1TechLi2: "Pandas",
            project1TechLi3: "Scikit-learn",
            project1TechLi4: "Matplotlib",
            project1TechLi5: "Jupyter Notebook",
            project1Contribute: "Si tienes sugerencias o encuentras algo que pueda mejorarse, no dudes en abrir un <em>issue</em> o contribuir al proyecto.",
            projectRepoButton: "Repositorio",
            projectAuthorButton: "Autor: Edisson Giraldo",
            project2Title: "Reconocimiento Facial",
            project2Desc1: "El proyecto <strong>Reconocimiento Facial</strong> se centra en el desarrollo de un sistema eficiente para identificar y verificar rostros mediante técnicas avanzadas de visión artificial e inteligencia artificial. Este sistema tiene aplicaciones en seguridad, autenticación biométrica y gestión de acceso.",
            project2FeatTitle: "Características Principales",
            project2FeatLi1: "<strong>Detección de Rostros:</strong> Identificación precisa de rostros en imágenes o videos en tiempo real.",
            project2FeatLi2: "<strong>Reconocimiento de Identidades:</strong> Comparación de rostros con una base de datos previamente entrenada.",
            project2FeatLi3: "<strong>Procesamiento en Tiempo Real:</strong> Optimización para lograr un desempeño rápido y confiable.",
            project2FeatLi4: "<strong>Seguridad y Privacidad:</strong> Almacenamiento seguro y tratamiento ético de los datos biométricos.",
            project2TechTitle: "Tecnologías Utilizadas",
            project2TechLi1: "Python",
            project2TechLi2: "OpenCV",
            project2TechLi3: "Dlib",
            project2TechLi4: "TensorFlow / PyTorch",
            project2TechLi5: "Flask",
            project2UseCaseTitle: "Casos de Uso",
            project2UseCaseLi1: "Control de acceso en sistemas de seguridad.",
            project2UseCaseLi2: "Autenticación en aplicaciones biométricas.",
            project2UseCaseLi3: "Monitoreo inteligente en entornos públicos o privados.",
            project2ContributeTitle: "¿Cómo Contribuir?",
            project2ContributeDesc: "Si deseas colaborar en el desarrollo de este proyecto, puedes explorar el código, reportar problemas, sugerir nuevas funcionalidades o realizar contribuciones mediante <em>pull requests</em>. Toda aportación es valiosa para hacer crecer esta herramienta.",
            project2LinksTitle: "Enlaces Relacionados",
            project2FinalDesc: "Proyecto desarrollado para explorar y aplicar técnicas avanzadas de visión por computadora e inteligencia artificial en contextos del mundo real.",
            project3Title: "ClimaIA",
            project3Desc1: "Proyecto de análisis climático que utiliza inteligencia artificial para realizar predicciones precisas y accesibles. Este sistema combina algoritmos avanzados de aprendizaje automático con datos meteorológicos para ofrecer una herramienta innovadora, beneficiando a comunidades y empresas en la planificación y toma de decisiones basadas en el clima.",
            project3FeatTitle: "Características del Proyecto",
            project3FeatLi1: "<strong>Procesamiento de Datos Meteorológicos:</strong> Integración de datos climáticos históricos y en tiempo real.",
            project3FeatLi2: "<strong>Modelos Predictivos:</strong> Uso de algoritmos avanzados como regresión, redes neuronales y modelos temporales para predicciones precisas.",
            project3FeatLi3: "<strong>Visualización Intuitiva:</strong> Gráficos interactivos que facilitan la interpretación de los resultados.",
            project3FeatLi4: "<strong>Escalabilidad:</strong> Sistema modular que puede adaptarse a diferentes regiones y necesidades climáticas.",
            project3TechTitle: "Tecnologías Utilizadas",
            project3TechLi1: "Python",
            project3TechLi2: "Pandas y NumPy",
            project3TechLi3: "TensorFlow / Scikit-learn",
            project3TechLi4: "Matplotlib y Seaborn",
            project3TechLi5: "APIs Climáticas",
            project3TechLi6: "Jupyter Notebook",
            project3ContributeTitle: "¿Cómo Contribuir?",
            project3ContributeDesc: "Si estás interesado en colaborar, puedes explorar el código, reportar problemas, sugerir mejoras o enviar tus propias contribuciones mediante <em>pull requests</em>. Toda ayuda es bienvenida para mejorar y escalar este proyecto.",
            project3LinksTitle: "Enlaces Relacionados",
            projectAuthorButtonAlt: "Autor: Resuelve IA",
            project3FinalDesc: "Proyecto desarrollado con pasión por la ciencia de datos y la inteligencia artificial para mejorar nuestra relación con el medio ambiente.",
            projectsLookAtRepos: "¡Echa un vistazo a mis repositorios para ver más de mi trabajo!",
            portfolioTitle: "Portafolio",
            portfolio1Title: "Desarrollo Web Fullstack",
            portfolio1Desc1: "Ofrezco servicios completos de desarrollo web fullstack, abordando cada etapa del ciclo de vida del proyecto: desde el diseño inicial y la implementación hasta el despliegue y la optimización. Trabajo con tecnologías modernas como <strong>HTML5</strong>, <strong>CSS3</strong>, <strong>JavaScript</strong> (incluyendo <strong>React</strong> y <strong>Node.js</strong>), y bases de datos como <strong>MongoDB</strong>.",
            portfolio1Desc2: "Mi experiencia incluye la creación de:",
            portfolio1Li1: "Plataformas de comercio electrónico escalables.",
            portfolio1Li2: "Sistemas de gestión de contenido (CMS).",
            portfolio1Li3: "Aplicaciones dinámicas con análisis en tiempo real.",
            portfolio1Li4: "Interfaces intuitivas centradas en el usuario.",
            portfolio1Desc3: "Ofrezco soluciones personalizadas con un enfoque ágil y orientado a resultados, asegurando productos robustos y de alta calidad.",
            portfolio2Title: "Desarrollo de Aplicaciones Móviles",
            portfolio2Desc1: "Diseñamos y desarrollamos aplicaciones móviles para <strong>Android</strong> e <strong>iOS</strong> que ofrecen experiencias fluidas y de alto rendimiento. Utilizo herramientas como <strong>Flutter</strong> y <strong>React Native</strong> para crear aplicaciones multiplataforma eficientes.",
            portfolio2Desc2: "Mis proyectos de aplicaciones móviles se caracterizan por:",
            portfolio2Li1: "Diseño centrado en la experiencia del usuario (UX/UI).",
            portfolio2Li2: "Integración de funciones avanzadas como notificaciones push y bases de datos en la nube.",
            portfolio2Li3: "Seguridad robusta para proteger datos sensibles.",
            portfolio2Li4: "Escalabilidad para crecer con las necesidades de tu negocio.",
            portfolio2Desc3: "Mi objetivo es crear aplicaciones que combinen funcionalidad y diseño, generando un impacto positivo para los usuarios finales.",
            portfolio3Title: "Inteligencia Artificial y Ciencia de Datos",
            portfolio3Desc1: "Ofrezco servicios especializados en <strong>implementación de soluciones de inteligencia artificial</strong> y análisis de datos, ayudando a empresas a transformar datos en conocimiento accionable. Utilizo herramientas avanzadas como <strong>Python</strong>, <strong>Pandas</strong>, <strong>TensorFlow</strong>, y <strong>PyTorch</strong> para desarrollar modelos inteligentes.",
            portfolio3Li1: "Modelos predictivos para optimizar decisiones empresariales.",
            portfolio3Li2: "Sistemas de recomendación personalizados.",
            portfolio3Li3: "Procesamiento de lenguaje natural (NLP) para análisis de texto y chatbots.",
            portfolio3Li4: "Visión por computadora para reconocimiento de imágenes y video.",
            portfolio3Desc3: "Mi enfoque combina la experiencia técnica con la comprensión de problemas empresariales, creando soluciones que generan valor real.",
            footerNavToggleLabel: "Alternar navegación de pie de página",
            footerContactToggleLabel: "Alternar información de contacto",
            goTopButtonTitle: "Ir arriba",
            goTopButtonText: "Ir arriba",
            footerNavWhoAmI: "Quién soy",
            footerNavProjects: "Proyectos",
            footerNavPortfolio: "Portafolio",
            footerNavDownloadCV: "Descargar CV",
            footerAddressLabel: "Dirección:",
            footerPhone: "Teléfono:",
            footerEmail: "Correo electrónico:",
            footerLinkedIn: "LinkedIn",
            footerGithub: "Github",
            footerWhatsApp: "WhatsApp"
        },
        en: {
            pageTitle: "Edisson Giraldo's Portfolio - Software Engineer",
            headerH1: "Edisson Giraldo",
            headerH2: "Software Engineer",
            themeToggleLabel: "Toggle theme",
            languageToggleLabel: "Change language",
            menuToggleLabel: "Toggle navigation",
            navWhoAmI: "About Me",
            navProjects: "Projects",
            navPortfolio: "Portfolio",
            navLinkedIn: "LinkedIn",
            navGithub: "Github",
            navWhatsApp: "WhatsApp",
            navDownloadCV: "Download CV",
            profilePicAlt: "Profile picture",
            aboutName: "Edisson Giraldo",
            aboutDate: "03/13/2024",
            aboutP1: "Software Engineer with over 6 years of experience, specializing in creating full-stack web solutions and innovations in Artificial Intelligence. Graduated with honors from Politécnico Grancolombiano, my focus is on transforming complex ideas into robust and scalable applications.",
            aboutP2: "My main expertise has been consolidated in the MEAN stack (MongoDB, Express.js, Angular, Node.js), developing clean and efficient architectures. I have led teams in delivering web projects that stand out for their quality and maintainability.",
            aboutP3: "Recently, my focus has expanded towards the forefront of Artificial Intelligence, where I actively explore and apply:",
            aboutLi1: "<strong>Advanced Language Models (LLMs):</strong> Integration of models such as OpenAI (GPT) and Mistral AI to enhance applications with natural language processing (NLP) capabilities, autonomous content generation, and sentiment analysis.",
            aboutLi2: "<strong>Intelligent Agent Development:</strong> Design and implementation of autonomous agents and multi-agent systems (MAS) to automate complex tasks, optimize workflows, and create interactive and personalized user experiences.",
            aboutLi3: "<strong>Machine Learning Techniques:</strong> Application of machine learning algorithms for predictive analysis, pattern recognition, and data-driven decision-making.",
            aboutP4: "I have integrated these technologies into various projects, enhancing application intelligence and optimizing business processes. For example, I have implemented OpenAI-based solutions to improve user interaction and automation systems with Mistral to increase operational efficiency.",
            aboutP5: "My passion is to stay at the forefront of technological innovation, especially in AI, cloud computing, and software development. I constantly seek challenging projects that allow me to apply my knowledge to make a significant impact and contribute to the success of teams and organizations.",
            projectsTitle: "Projects",
            project1Title: "Applied Data Science Capstone",
            project1Desc1: "This repository contains the final project for the <em>Applied Data Science Capstone</em> course, designed to apply the skills and knowledge acquired in data science to a practical case.",
            project1Li1: "<strong>Problem Definition:</strong> Identification of a relevant problem to be solved through data analysis.",
            project1Li2: "<strong>Data Collection:</strong> Obtaining and processing data from relevant sources.",
            project1Li3: "<strong>Exploratory Data Analysis:</strong> Initial cleaning and exploration to discover significant patterns and relationships.",
            project1Li4: "<strong>Modeling:</strong> Application of machine learning techniques to solve the stated problem.",
            project1Li5: "<strong>Visualization:</strong> Creation of interactive charts and dashboards to effectively communicate results.",
            project1Li6: "<strong>Conclusions:</strong> Recommendations based on the findings obtained during the analysis.",
            project1Desc2: "This project combines advanced data analysis, predictive modeling, and visualization techniques, using tools such as <strong>Python</strong>, <strong>Pandas</strong>, <strong>Scikit-learn</strong>, and <strong>Matplotlib</strong>, among others.",
            project1FeatTitle: "Project Features",
            project1FeatLi1: "Focus on solving real-world problems.",
            project1FeatLi2: "Modular and reproducible design to facilitate understanding and scalability.",
            project1FeatLi3: "Fully documented code aligned with best practices.",
            project1TechTitle: "Technologies Used",
            project1TechLi1: "Python",
            project1TechLi2: "Pandas",
            project1TechLi3: "Scikit-learn",
            project1TechLi4: "Matplotlib",
            project1TechLi5: "Jupyter Notebook",
            project1Contribute: "If you have suggestions or find something that can be improved, feel free to open an <em>issue</em> or contribute to the project.",
            projectRepoButton: "Repository",
            projectAuthorButton: "Author: Edisson Giraldo",
            project2Title: "Facial Recognition",
            project2Desc1: "The <strong>Facial Recognition</strong> project focuses on developing an efficient system to identify and verify faces using advanced computer vision and artificial intelligence techniques. This system has applications in security, biometric authentication, and access management.",
            project2FeatTitle: "Main Features",
            project2FeatLi1: "<strong>Face Detection:</strong> Accurate identification of faces in images or real-time video.",
            project2FeatLi2: "<strong>Identity Recognition:</strong> Comparison of faces with a previously trained database.",
            project2FeatLi3: "<strong>Real-Time Processing:</strong> Optimization for fast and reliable performance.",
            project2FeatLi4: "<strong>Security and Privacy:</strong> Secure storage and ethical treatment of biometric data.",
            project2TechTitle: "Technologies Used",
            project2TechLi1: "Python",
            project2TechLi2: "OpenCV",
            project2TechLi3: "Dlib",
            project2TechLi4: "TensorFlow / PyTorch",
            project2TechLi5: "Flask",
            project2UseCaseTitle: "Use Cases",
            project2UseCaseLi1: "Access control in security systems.",
            project2UseCaseLi2: "Authentication in biometric applications.",
            project2UseCaseLi3: "Intelligent monitoring in public or private environments.",
            project2ContributeTitle: "How to Contribute?",
            project2ContributeDesc: "If you want to collaborate on the development of this project, you can explore the code, report problems, suggest new features, or make contributions through <em>pull requests</em>. All contributions are valuable to grow this tool.",
            project2LinksTitle: "Related Links",
            project2FinalDesc: "Project developed to explore and apply advanced computer vision and artificial intelligence techniques in real-world contexts.",
            project3Title: "ClimaIA",
            project3Desc1: "Climate analysis project that uses artificial intelligence to make accurate and accessible predictions. This system combines advanced machine learning algorithms with meteorological data to offer an innovative tool, benefiting communities and businesses in climate-based planning and decision-making.",
            project3FeatTitle: "Project Features",
            project3FeatLi1: "<strong>Meteorological Data Processing:</strong> Integration of historical and real-time climate data.",
            project3FeatLi2: "<strong>Predictive Models:</strong> Use of advanced algorithms such as regression, neural networks, and time series models for accurate predictions.",
            project3FeatLi3: "<strong>Intuitive Visualization:</strong> Interactive graphics that facilitate the interpretation of results.",
            project3FeatLi4: "<strong>Scalability:</strong> Modular system that can be adapted to different regions and climate needs.",
            project3TechTitle: "Technologies Used",
            project3TechLi1: "Python",
            project3TechLi2: "Pandas and NumPy",
            project3TechLi3: "TensorFlow / Scikit-learn",
            project3TechLi4: "Matplotlib and Seaborn",
            project3TechLi5: "Climate APIs",
            project3TechLi6: "Jupyter Notebook",
            project3ContributeTitle: "How to Contribute?",
            project3ContributeDesc: "If you are interested in collaborating, you can explore the code, report problems, suggest improvements, or submit your own contributions through <em>pull requests</em>. All help is welcome to improve and scale this project.",
            project3LinksTitle: "Related Links",
            projectAuthorButtonAlt: "Author: Resuelve IA",
            project3FinalDesc: "Project developed with a passion for data science and artificial intelligence to improve our relationship with the environment.",
            projectsLookAtRepos: "Take a look at my repositories to see more of my work!",
            portfolioTitle: "Portfolio",
            portfolio1Title: "Fullstack Web Development",
            portfolio1Desc1: "I offer comprehensive full-stack web development services, addressing every stage of the project lifecycle: from initial design and implementation to deployment and optimization. I work with modern technologies such as <strong>HTML5</strong>, <strong>CSS3</strong>, <strong>JavaScript</strong> (including <strong>React</strong> and <strong>Node.js</strong>), and databases like <strong>MongoDB</strong>.",
            portfolio1Desc2: "My experience includes creating:",
            portfolio1Li1: "Scalable e-commerce platforms.",
            portfolio1Li2: "Content management systems (CMS).",
            portfolio1Li3: "Dynamic applications with real-time analytics.",
            portfolio1Li4: "User-centered intuitive interfaces.",
            portfolio1Desc3: "I offer customized solutions with an agile, results-oriented approach, ensuring robust, high-quality products.",
            portfolio2Title: "Mobile Application Development",
            portfolio2Desc1: "We design and develop mobile applications for <strong>Android</strong> and <strong>iOS</strong> that offer smooth, high-performance experiences. I use tools like <strong>Flutter</strong> and <strong>React Native</strong> to create efficient cross-platform applications.",
            portfolio2Desc2: "My mobile application projects are characterized by:",
            portfolio2Li1: "User-centered design (UX/UI).",
            portfolio2Li2: "Integration of advanced features like push notifications and cloud databases.",
            portfolio2Li3: "Robust security to protect sensitive data.",
            portfolio2Li4: "Scalability to grow with your business needs.",
            portfolio2Desc3: "My goal is to create applications that combine functionality and design, generating a positive impact for end-users.",
            portfolio3Title: "Artificial Intelligence and Data Science",
            portfolio3Desc1: "I offer specialized services in <strong>implementing artificial intelligence solutions</strong> and data analysis, helping companies transform data into actionable knowledge. I use advanced tools like <strong>Python</strong>, <strong>Pandas</strong>, <strong>TensorFlow</strong>, and <strong>PyTorch</strong> to develop intelligent models.",
            portfolio3Li1: "Predictive models to optimize business decisions.",
            portfolio3Li2: "Personalized recommendation systems.",
            portfolio3Li3: "Natural language processing (NLP) for text analysis and chatbots.",
            portfolio3Li4: "Computer vision for image and video recognition.",
            portfolio3Desc3: "My approach combines technical expertise with an understanding of business problems, creating solutions that generate real value.",
            footerNavToggleLabel: "Toggle footer navigation",
            footerContactToggleLabel: "Toggle contact information",
            goTopButtonTitle: "Go to top",
            goTopButtonText: "Go to top",
            footerNavWhoAmI: "About Me",
            footerNavProjects: "Projects",
            footerNavPortfolio: "Portfolio",
            footerNavDownloadCV: "Download CV",
            footerAddressLabel: "Address:",
            footerPhone: "Phone:",
            footerEmail: "Email:",
            footerLinkedIn: "LinkedIn",
            footerGithub: "Github",
            footerWhatsApp: "WhatsApp"
        }
    };

    let currentLanguage = localStorage.getItem('language') || (navigator.language.startsWith('es') ? 'es' : 'en');

    function applyTranslations(lang) {
        document.documentElement.lang = lang;
        document.title = translations[lang].pageTitle;

        document.querySelectorAll('[data-i18n-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-key');
            if (translations[lang] && translations[lang][key]) {
                element.innerHTML = translations[lang][key];
            }
        });
        
        document.querySelectorAll('[data-i18n-aria-label-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-aria-label-key');
            if (translations[lang] && translations[lang][key]) {
                element.setAttribute('aria-label', translations[lang][key]);
            }
        });

        document.querySelectorAll('[data-i18n-alt-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-alt-key');
            if (translations[lang] && translations[lang][key]) {
                element.setAttribute('alt', translations[lang][key]);
            }
        });

        document.querySelectorAll('[data-i18n-title-key]').forEach(element => {
            const key = element.getAttribute('data-i18n-title-key');
            if (translations[lang] && translations[lang][key]) {
                element.setAttribute('title', translations[lang][key]);
            }
        });

        if (languageToggleButton) {
            languageToggleButton.textContent = lang === 'es' ? '🇪🇸' : '🇬🇧';
        }
        localStorage.setItem('language', lang);
    }

    if (languageToggleButton) {
        languageToggleButton.addEventListener('click', () => {
            currentLanguage = currentLanguage === 'es' ? 'en' : 'es';
            applyTranslations(currentLanguage);
        });
    }

    // Aplicar traducciones al cargar la página
    applyTranslations(currentLanguage);
}); 